support sequential executions
velo/feign-mock pull request #9
Opened 2017-12-18 09:58 UTC by vermgit

Bug fixes:
* RequestKey.hash() must return equal values when equal() returns true

Improvements:
* RequestKey:
  * use Java's hash()
  * extended checks to cover headers, charset and body
  * added builder pattern

* MockClient:
  * use Java's HTTP status codes
  * support sequential executions
  * added more add(), ok() and notOk() methods
  * added verifyStatus(), which currently doesn't check anything for non-sequential tests
  * minor streamlining

* updated readme

---

* As I lined out above verifyStatus() currently has no code to check anything for non-sequential tests. As I only use it the sequential way I can't tell what makes sense to test here.
* In case this pull request makes it into the library, it may make sense to set the new version to 1.0 and have the sequential field in MockClient default to true.

2017-12-18 17:39 UTC, velo commented
Hey man, can you build this locally with maven to fix code format error?

Also, seems you changed line ending on readme.md.

2017-12-18 18:49 UTC, vermgit commented
I can't say if the readme is better now, but that's all I can do on that part. The file has Unix' file endings on my end.

2017-12-18 19:54 UTC, velo commented
Ha, my bad, the original file got windows endings somehow.

I got that fixed, but that created a conflict on the PR... =(



[image: --]

Marvin Froeder
[image: https://]about.me/velo
<https://about.me/velo?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

On Tue, Dec 19, 2017 at 7:49 AM, vermgit <notifications@github.com> wrote:

> I can't say if the readme is better now, but that's all I can do on that
> part. The file has Unix' file endings on my end.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/velo/feign-mock/pull/9#issuecomment-352522287>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAIVjjE0ikQEdAsgQVHXQX0yHq6q06VNks5tBrPXgaJpZM4RFOL9>
> .
>

2017-12-18 20:01 UTC, vermgit commented
I don't know what git does. I fixed it twice now.

2017-12-19 20:50 UTC, velo requested changes

2017-12-19 20:50 UTC, velo commented on src/test/java/feign/mock/MockClientTest.java
> +    private MockClient mockClientSequential;
I would suggest breaking this into 2 tests.
1st - The original `MockClientTest` w/o any changes as this needs to be binary compatible with previous version
2nd - `SequentialMockClientTest` which would only include `githubSequential` and `mockClientSequential` plus associated `@Test`s.

2017-12-19 20:50 UTC, velo commented on src/main/java/feign/mock/MockClient.java
> +    public MockClient notOk(HttpMethod method, String url, int status, InputStream responseBody) throws IOException {
I think instead of `notOk` this should be either called `add` like the existing add methods... or call it `withStatus`

When I read not ok I though there was an HTTP code `40x NOT_OK`

specially because I could call `notOk(method, url, 201)`, which is kinda ok

2017-12-19 20:50 UTC, velo commented on src/main/java/feign/mock/RequestKey.java
> +    private byte[] body;
can you make all this fields `final`?!

2017-12-20 15:58 UTC, velo approved these changes

2017-12-20 16:01 UTC, merged